site_name: Conant Robotics Documentation
site_url: https://example.com
nav:
        - Home: index.md
        - About: about.md
theme: readthedocs
markdown_extensions:
        - toc:
                permalink: True
        - pymdownx.tilde
